"""Test the End Point Type functions."""

from unittest import TestCase

type_hints = [
    "int",
    "float",
    "str",
    "bool",
    "bytes",
    "list[int]",
    "list[float]",
    "list[str]",
    "list[bool]",
    "tuple[int, str]",
    "tuple[float, bool]",
    "tuple[str, int, float]",
    "dict[str, int]",
    "dict[int, float]",
    "dict[str, str]",
    "dict[str, list[int]]",
    "dict[int, tuple[float, bool]]",
    "list[list[int]]",
    "list[list[str]]",
    "list[tuple[int, float]]",
    "tuple[list[int], list[str]]",
    "tuple[dict[str, int], list[float]]",
    "dict[str, dict[int, float]]",
    "dict[int, list[tuple[str, bool]]]",
    "list[dict[str, list[int]]]",
    "set[int]",
    "set[str]",
    "frozenset[float]",
    "list[set[int]]",
    "dict[str, set[bool]]",
    "tuple[set[int], frozenset[str]]",
    "set[list[int]]",
    "dict[str, frozenset[tuple[int, float]]]",
    "list[set[dict[str, int]]]",
    "Iterator[int]",
    "Iterator[str]",
    "Iterable[float]",
    "list[Iterator[int]]",
    "dict[str, Iterable[bool]]",
    "tuple[Iterator[int], Iterable[str]]",
    "Sequence[int]",
    "Sequence[str]",
    "MutableSequence[float]",
    "list[Sequence[int]]",
    "dict[str, MutableSequence[bool]]",
    "tuple[Sequence[int], MutableSequence[str]]",
    "Mapping[str, int]",
    "Mapping[int, float]",
    "MutableMapping[str, bool]",
    "list[Mapping[str, int]]",
    "dict[str, MutableMapping[int, float]]",
    "tuple[Mapping[str, int], MutableMapping[int, float]]",
    "list[dict[str, list[int]]]",
    "list[dict[str, tuple[int, float]]]",
    "list[dict[str, dict[int, str]]]",
    "dict[str, list[tuple[int, float]]]",
    "dict[str, list[dict[int, str]]]",
    "dict[str, dict[int, list[float]]]",
    "tuple[list[dict[str, int]], tuple[int, float]]",
    "tuple[dict[str, list[int]], dict[int, tuple[float, str]]]",
    "tuple[list[int], list[dict[str, float]]]",
    "list[tuple[dict[str, int], list[float]]]",
    "dict[str, tuple[list[int], dict[int, float]]]",
]


class TestEndPointType(TestCase):
    """Test the End Point Type functions."""
