[tool.black]
line-length = 100
target-version = ['py312'] # Set your target Python version


[tool.isort]
profile = "black"
line_length = 100


[tool.pyright]
# These settings will apply to Pylance in VS Code and the pre-commit hook.
exclude = [
    "**/__pycache__",
    "**/.pytest_cache",
]
typeCheckingMode = "strict"
venvPath = "."
venv = ".venv"
reportUnknownArgumentType = "none"
reportUnknownVariableType = "none"
reportUnknownMemberType = "none"
reportUnnecessaryIsInstance = "none"


[tool.pylint.format]
max-line-length = 100


[tool.pylint.messages-control]
disable = [
    "W2301", # Unnecessary use of ellipsis - for readability
    "W0107", # Unnecessary pass statement - for readability
    "fixme", # Disable all fixme messages - just whilst in development
]