type: object
properties:
  name:
    type: string
    maxLength: 128
    minLength: 1
    pattern: "^[ -~]{1,128}$"
    description: "The human readable name of the datastore as an arbitary string."
  database:
    type: object
    properties:
      dbtype:
        type: string
        enum:
          - postgres
          - sqliteMemory
        default: "postgres"
        description: "The type of database to connect to."
      dbname:
        type: string
        minLength: 1
        maxLength: 64
        pattern: "[a-zA-Z][a-zA-Z0-9_-]*"
        default: "postgres"
        description: "The name of the database."
      host:
        type: string
        default: "localhost"
        pattern: "(^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9])\\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9-]*[A-Za-z0-9])$|^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$)"
        description: "A valid RFC952 hostname or IP address."
      maintenance_user:
        type: string
        default: "postgres"
        description: "The username to access the maintenance DB."
      user:
        type: string
        default: "postgres"
        description: "The username to access the maintenance DB."
      port:
        type: integer
        default: 5432
        minimum: 1024
        maximum: 65535
      maintenance_db:
        type: string
        default: "postgres"
      retries:
        type: integer
        default: 0
        minimum: 0
        maximum: 2147483647
        description: "The number of times to retry a connection attempt."
      delete:
        type: boolean
        default: false
        description: "If True, the database will be deleted if it exists."
      create:
        type: boolean
        default: true
        description: "If True, the database will be created if it does not exist."
      wait:
        type: boolean
        default: false
        description: "If True, the value of 'create' will be ignored and the operation will wait for the database to exist."
    required:
      - dbname
  schemas:
    type: array
    description: "The list of table schema files to create in the database."
    items:
      type: string
      maxLength: 128
      pattern: "^[ -~]*\\.yaml$"
required:
- name
- database
- schemas
