"""Common Object  Class."""

from egpcommon.common import debug_exceptions
from egpcommon.egp_log import Logger, egp_logger

# Standard EGP logging pattern
_logger: Logger = egp_logger(name=__name__)


class CommonObj:
    """Common Object Class.

    The Common Object Class, CommonObj, is the base class for all custom objects in EGP.
    EGP has the philosophy that all objects should be able to verify their own data and check
    their own consistency. The methods defined here shall always be called by derived classes.

    Derived classes shall validate their data on input to the class (via init or setters). If
    a parameter is derived from a CommonObj derived class then it shall be verified by calling
    its verify() method.
    """

    __slots__ = tuple()

    @staticmethod
    def value_error(condition: bool, message: str) -> None:
        """Helper method to verify a condition and raise ValueError if false.

        *NOTE*: Standard exceptions may be generated by genetic code and are thus a
        valid runtime exception within EGP. Debug exceptions are errors in the EGP application.

        Args:
            condition: The condition to verify.
            message: The error message to include in the ValueError if condition is False.

        Raises:
            ValueError: If condition is False.
        """
        if not condition:
            raise ValueError(message)

    @staticmethod
    def debug_value_error(condition: bool, message: str) -> None:
        """Helper method to verify a condition and raise DebugValueError if false.

        *NOTE*: Standard exceptions may be generated by genetic code and are thus a
        valid runtime exception within EGP. Debug exceptions are errors in the EGP application.

        Args:
            condition: The condition to verify.
            message: The error message to include in the DebugValueError if condition is False.

        Raises:
            DebugValueError: If condition is False.
        """
        if not condition:
            raise debug_exceptions.DebugValueError(message)

    @staticmethod
    def runtime_error(condition: bool, message: str) -> None:
        """Helper method to check consistency and raise RuntimeError if false.

        *NOTE*: Standard exceptions may be generated by genetic code and are thus a
        valid runtime exception within EGP. Debug exceptions are errors in the EGP application.

        Args:
            condition: The condition to check.
            message: The error message to include in the RuntimeError if condition is False.

        Raises:
            RuntimeError: If condition is False.
        """
        if not condition:
            raise RuntimeError(message)

    @staticmethod
    def debug_runtime_error(condition: bool, message: str) -> None:
        """Helper method to check consistency and raise DebugRuntimeError if false.

        *NOTE*: Standard exceptions may be generated by genetic code and are thus a
        valid runtime exception within EGP. Debug exceptions are errors in the EGP application.

        Args:
            condition: The condition to check.
            message: The error message to include in the DebugRuntimeError if condition is False.

        Raises:
            DebugRuntimeError: If condition is False.
        """
        if not condition:
            raise debug_exceptions.DebugRuntimeError(message)

    @staticmethod
    def type_error(condition: bool, message: str) -> None:
        """Helper method to verify a condition and raise TypeError if false.

        *NOTE*: Standard exceptions may be generated by genetic code and are thus a
        valid runtime exception within EGP. Debug exceptions are errors in the EGP application.

        Args:
            condition: The condition to verify.
            message: The error message to include in the TypeError if condition is False.
        Raises:
            TypeError: If condition is False.
        """
        if not condition:
            raise TypeError(message)

    @staticmethod
    def debug_type_error(condition: bool, message: str) -> None:
        """Helper method to verify a condition and raise DebugTypeError if false.

        *NOTE*: Standard exceptions may be generated by genetic code and are thus a
        valid runtime exception within EGP. Debug exceptions are errors in the EGP application.

        Args:
            condition: The condition to verify.
            message: The error message to include in the DebugTypeError if condition is False.
        Raises:
            DebugTypeError: If condition is False.
        """
        if not condition:
            raise debug_exceptions.DebugTypeError(message)

    def consistency(self):
        """Check the consistency of the CommonObj.

        The consistency() method is used to check the semantic of the CommonObj
        object. An object verified by verify() may not raise an exception because each of its
        values is individually correct but may raise one in a consistency() check because of
        an invalid relationship between values that is expensive to check. Typically examples
        would involve heavy IO or complex calculations.

        The consistency() method shall raise an exception if the object is not
        consistent. The exception message shall
        indicate the reason for the failure. Ideally containing the invalid value and
        the valid range of values if it can be displayed concisely.

        Derived classes shall override this method to add their own checks but
        shall always call the base class consistency() method at the *end* of their own
        consistency() method. This is to ensure that the consistency() method is only called
        once all other checks have passed.

        Derived classes shall use the static helper methods defined in this class to
        raise exceptions in this method. e.g. value_error(), debug_type_error() etc.
        See `egpcommon.common.debug_exceptions` for appropriate usage.
        See `egpcommon.egp_log` for logging level usage.

        NOTE: Likely to significantly slow down the code.
        """

    def verify(self):
        """Verify the CommonObj object.

        The verify() method is used to check the CommonObj objects data for validity.
        e.g. correct value ranges, lengths, types etc. with relatively fast checks.

        *IMPORTANT*
        The verify() method shall raise an exception if the object is not valid at the
        first check that fails (for performance reasons). The exception message shall
        indicate the reason for the failure. Ideally containing the invalid value and
        the valid range of values if it can be displayed concisely.

        Derived classes shall override this method to add their own checks but
        shall always call the base class verify() method at the *end* of their own
        verify() method.

        Derived classes shall use the static helper methods defined in this class to
        raise exceptions in this method. e.g. value_error(), debug_type_error() etc.
        See `egpcommon.common.debug_exceptions` for appropriate usage.
        See `egpcommon.egp_log` for logging level usage.
        """
