version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      -  ${DEVCONTAINER_CONTAINER_WORKSPACE_FOLDER:-/workspaces/erasmus-gp}:/workspace:cached
    command: sleep infinity
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: egp-local-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: egp-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=nobody@nowhere.com
      - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/db-password
      - PGADMIN_DISABLE_POSTFIX=true
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - default

volumes:
  postgres_data:
