services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      -  ..:/workspaces:cached
    environment:
      EGP_PRIVATE_KEY_FILE: /run/secrets/private_key
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qlkjidfkoqwfbg}
      PRIVATE_KEY_PEM_B64: ${PRIVATE_KEY_PEM_B64:-}
      RELEASE_DATA_MANAGER_TOKEN: ${RELEASE_DATA_MANAGER_TOKEN:-}
    command: sleep infinity
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qlkjidfkoqwfbg}
    ports:
      - "${POSTGRES_HOST_PORT:-0}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - default
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=nobody@nowhere.com
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-qlkjidfkoqwfbg}
      - PGADMIN_DISABLE_POSTFIX=true
    ports:
      - "${PGADMIN_HOST_PORT:-0}:80"
    depends_on:
      - postgres
    networks:
      - default
    entrypoint: >
      /bin/sh -c "
        echo 'postgres:5432:*:postgres:'${POSTGRES_PASSWORD:-qlkjidfkoqwfbg} > /tmp/pgpass_generated;
        chmod 600 /tmp/pgpass_generated;
        chown 5050:5050 /tmp/pgpass_generated;
        /entrypoint.sh;
      "
volumes:
  postgres_data:
