type: object
properties:
  table:
    type: string
    minLength: 1
    maxLength: 63
    pattern: "[a-zA-Z_][a-zA-Z0-9_-]*"
    description: The name of the table.
  delete:
    type: boolean
    description: If True, the table will be deleted if it exists.
  create:
    type: boolean
    description: If True, the table will be created if it does not exist.
  wait:
    type: boolean
    description: If True, the value of 'create' will be ignored and the operation will wait for the table to exist.
  schema:
    type: object
    minLength: 1
    maxLength: 1600
    properties:
      keys:
        type: string
        minLength: 1
        maxLength: 63
        pattern: "[a-zA-Z_][a-zA-Z0-9_-]*"
      values:
        type: object
        properties:
          type:
            type: string
            enum:
              - BIGINT
              - BOOLEAN
              - BYTEA
              - VARCHAR
              - DATETIME
              - DOUBLE PRECISION
              - INTEGER
              - REAL
              - SMALLINT
              - TEXT
              - UUID
            description: Supported postgresql type expression.
          nullable:
            type: boolean
            description: Allow NULL entries if True.
          primary_key:
            type: boolean
            description: Column is the primary key and automatically indexed if True. Primary key columns cannot have NULL entries.
          unique:
            type: boolean
            description: Entries in the column are unique and automatically indexed if True. Cannot also be primary keys.
          volatile:
            type: boolean
            description: Application hint that the column may be updated after initialisation when True.
          index:
            type: string
            enum:
              - btree
              - hash
              - gist
              - gin
            description: Column is indexed with the selected algorithm. PRIMARY KEY or UNIQUE columns cannot be additionally indexed.
          default:
            type: string
            maxLength: 256
            description: Default value of the column specified as an SQL string after 'DEFAULT ' in the CREATE TABLE statement.
required:
- table
- schema